# Generated by Django 3.1.1 on 2020-10-15 12:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='test text'),
            preserve_default=False,
        ),
    ]
