# Generated by Django 3.1.1 on 2020-10-09 14:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201009_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='helo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(),
        ),
    ]
