# Generated by Django 3.1.1 on 2020-10-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=30, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='تلفن تماس')),
                ('status', models.CharField(choices=[('f', 'فوری'), ('m', 'معمولی')], max_length=1, verbose_name='میزان اهمیت')),
                ('description', models.TextField(verbose_name='متن درخواست')),
            ],
        ),
    ]
