# Generated by Django 3.1.1 on 2020-10-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='تلفن تماس'),
            preserve_default=False,
        ),
    ]
