# Generated by Django 3.1.1 on 2020-10-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201015_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, default=1, max_length=20, verbose_name='تلفن تماس'),
            preserve_default=False,
        ),
    ]
