# Generated by Django 3.1.1 on 2020-10-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201015_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('name',), 'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس ها'},
        ),
    ]
