# Generated by Django 3.1.1 on 2020-10-15 14:19

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201015_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
