# Generated by Django 3.1.1 on 2020-10-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201015_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slider',
        ),
    ]
